#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

#include "resorces/functions.h"

/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 24), // bool()(point, point, point, point)
/*  1 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 16), // point
/*  2 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  3 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  4 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  5 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  6 */ _CFFI_OP(_CFFI_OP_FUNCTION, 86), // checkpoint()(point, point, point)
/*  7 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  8 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  9 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 10 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 11 */ _CFFI_OP(_CFFI_OP_FUNCTION, 86), // checkpoint()(point, point, point, point)
/* 12 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 13 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 14 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 15 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 16 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 17 */ _CFFI_OP(_CFFI_OP_FUNCTION, 74), // collision()(shape *, shape *)
/* 18 */ _CFFI_OP(_CFFI_OP_POINTER, 117), // shape *
/* 19 */ _CFFI_OP(_CFFI_OP_NOOP, 18),
/* 20 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 21 */ _CFFI_OP(_CFFI_OP_FUNCTION, 74), // collision()(shape *, shape *, bool, bool)
/* 22 */ _CFFI_OP(_CFFI_OP_NOOP, 18),
/* 23 */ _CFFI_OP(_CFFI_OP_NOOP, 18),
/* 24 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // bool
/* 25 */ _CFFI_OP(_CFFI_OP_NOOP, 24),
/* 26 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 27 */ _CFFI_OP(_CFFI_OP_FUNCTION, 66), // dd *()(shape * *, int, point, float)
/* 28 */ _CFFI_OP(_CFFI_OP_POINTER, 18), // shape * *
/* 29 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 30 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 31 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13), // float
/* 32 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 33 */ _CFFI_OP(_CFFI_OP_FUNCTION, 31), // float()(float, float)
/* 34 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13),
/* 35 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13),
/* 36 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 37 */ _CFFI_OP(_CFFI_OP_FUNCTION, 31), // float()(point, point)
/* 38 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 39 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 40 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 41 */ _CFFI_OP(_CFFI_OP_FUNCTION, 103), // lines()(array2, point)
/* 42 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 5), // array2
/* 43 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 44 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 45 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // point()(array2)
/* 46 */ _CFFI_OP(_CFFI_OP_NOOP, 42),
/* 47 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 48 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // point()(point, point)
/* 49 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 50 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 51 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 52 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // point()(point, point, float, float)
/* 53 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 54 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 55 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13),
/* 56 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13),
/* 57 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 58 */ _CFFI_OP(_CFFI_OP_FUNCTION, 18), // shape *()(array2, float, float, float, float)
/* 59 */ _CFFI_OP(_CFFI_OP_NOOP, 42),
/* 60 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13),
/* 61 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13),
/* 62 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13),
/* 63 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13),
/* 64 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 65 */ _CFFI_OP(_CFFI_OP_FUNCTION, 128), // void()(dd *)
/* 66 */ _CFFI_OP(_CFFI_OP_POINTER, 87), // dd *
/* 67 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 68 */ _CFFI_OP(_CFFI_OP_FUNCTION, 128), // void()(shape *)
/* 69 */ _CFFI_OP(_CFFI_OP_NOOP, 18),
/* 70 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 71 */ _CFFI_OP(_CFFI_OP_FUNCTION, 128), // void()(shape *, shape *, collision)
/* 72 */ _CFFI_OP(_CFFI_OP_NOOP, 18),
/* 73 */ _CFFI_OP(_CFFI_OP_NOOP, 18),
/* 74 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 7), // collision
/* 75 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 76 */ _CFFI_OP(_CFFI_OP_FUNCTION, 128), // void()(xx *)
/* 77 */ _CFFI_OP(_CFFI_OP_POINTER, 129), // xx *
/* 78 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 79 */ _CFFI_OP(_CFFI_OP_FUNCTION, 77), // xx *()(point, int)
/* 80 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 81 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 82 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 83 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 4), // array
/* 84 */ _CFFI_OP(_CFFI_OP_ARRAY, 24), // bool[10]
/* 85 */ (_cffi_opcode_t)(10),
/* 86 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 6), // checkpoint
/* 87 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 8), // dd
/* 88 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 9), // ff
/* 89 */ _CFFI_OP(_CFFI_OP_ARRAY, 31), // float[10]
/* 90 */ (_cffi_opcode_t)(10),
/* 91 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 10), // gg
/* 92 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 11), // inrng
/* 93 */ _CFFI_OP(_CFFI_OP_ARRAY, 29), // int[3]
/* 94 */ (_cffi_opcode_t)(3),
/* 95 */ _CFFI_OP(_CFFI_OP_ARRAY, 93), // int[500][3]
/* 96 */ (_cffi_opcode_t)(500),
/* 97 */ _CFFI_OP(_CFFI_OP_ARRAY, 95), // int[800][500][3]
/* 98 */ (_cffi_opcode_t)(800),
/* 99 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 12), // line
/* 100 */ _CFFI_OP(_CFFI_OP_ARRAY, 99), // line[50]
/* 101 */ (_cffi_opcode_t)(50),
/* 102 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 13), // lined
/* 103 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 14), // lines
/* 104 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 15), // nn
/* 105 */ _CFFI_OP(_CFFI_OP_ARRAY, 1), // point[10]
/* 106 */ (_cffi_opcode_t)(10),
/* 107 */ _CFFI_OP(_CFFI_OP_ARRAY, 1), // point[2]
/* 108 */ (_cffi_opcode_t)(2),
/* 109 */ _CFFI_OP(_CFFI_OP_POINTER, 110), // polar *
/* 110 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 17), // polar
/* 111 */ _CFFI_OP(_CFFI_OP_ARRAY, 110), // polar[100]
/* 112 */ (_cffi_opcode_t)(100),
/* 113 */ _CFFI_OP(_CFFI_OP_ARRAY, 110), // polar[10]
/* 114 */ (_cffi_opcode_t)(10),
/* 115 */ _CFFI_OP(_CFFI_OP_ARRAY, 18), // shape *[50]
/* 116 */ (_cffi_opcode_t)(50),
/* 117 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 18), // shape
/* 118 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // struct $1
/* 119 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // struct $2
/* 120 */ _CFFI_OP(_CFFI_OP_ARRAY, 119), // struct $2[10]
/* 121 */ (_cffi_opcode_t)(10),
/* 122 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // struct $3
/* 123 */ _CFFI_OP(_CFFI_OP_ARRAY, 122), // struct $3[2]
/* 124 */ (_cffi_opcode_t)(2),
/* 125 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 3), // struct $4
/* 126 */ _CFFI_OP(_CFFI_OP_ARRAY, 125), // struct $4[20]
/* 127 */ (_cffi_opcode_t)(20),
/* 128 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
/* 129 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 19), // xx
};

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_array(array *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { float(*tmp)[10] = &p->flt; (void)tmp; }
  { bool(*tmp)[10] = &p->bl; (void)tmp; }
  { point(*tmp)[10] = &p->pnt; (void)tmp; }
}
struct _cffi_align_typedef_array { char x; array y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_array2(array2 *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { point(*tmp)[10] = &p->pnt; (void)tmp; }
  (void)((p->no) | 0);  /* check that 'array2.no' is an integer */
}
struct _cffi_align_typedef_array2 { char x; array2 y; };

static int _cffi_const_false(unsigned long long *o)
{
  int n = (false) <= 0;
  *o = (unsigned long long)((false) | 0);  /* check that false is an integer */
  return n;
}

static int _cffi_const_true(unsigned long long *o)
{
  int n = (true) <= 0;
  *o = (unsigned long long)((true) | 0);  /* check that true is an integer */
  return n;
}

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_checkpoint(checkpoint *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { point *tmp = &p->pnt; (void)tmp; }
  { bool *tmp = &p->check; (void)tmp; }
}
struct _cffi_align_typedef_checkpoint { char x; checkpoint y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_collision(collision *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { bool *tmp = &p->check; (void)tmp; }
  { polar *tmp = &p->mtv; (void)tmp; }
  /* cannot generate 'struct $1' in field 'contacts': unknown type name */
}
struct _cffi_align_typedef_collision { char x; collision y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_dd(dd *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { polar * *tmp = &p->pnt; (void)tmp; }
  (void)((p->no) | 0);  /* check that 'dd.no' is an integer */
}
struct _cffi_align_typedef_dd { char x; dd y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_ff(ff *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  /* cannot generate 'struct $4[20]' in field 'shaped': unknown type name */
  (void)((p->no) | 0);  /* check that 'ff.no' is an integer */
}
struct _cffi_align_typedef_ff { char x; ff y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_gg(gg *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { polar *tmp = &p->mtv; (void)tmp; }
  { polar * *tmp = &p->pnt; (void)tmp; }
  (void)((p->no) | 0);  /* check that 'gg.no' is an integer */
  { point *tmp = &p->center; (void)tmp; }
  { lines *tmp = &p->axis; (void)tmp; }
  /* cannot generate 'struct $2[10]' in field 'prj': unknown type name */
}
struct _cffi_align_typedef_gg { char x; gg y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_inrng(inrng *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { shape *(*tmp)[50] = &p->ptr; (void)tmp; }
  (void)((p->no) | 0);  /* check that 'inrng.no' is an integer */
}
struct _cffi_align_typedef_inrng { char x; inrng y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_line(line *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { polar *tmp = &p->p1; (void)tmp; }
  { polar *tmp = &p->p2; (void)tmp; }
}
struct _cffi_align_typedef_line { char x; line y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_lined(lined *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { polar(*tmp)[100] = &p->p1; (void)tmp; }
  { polar(*tmp)[100] = &p->p2; (void)tmp; }
  (void)((p->no) | 0);  /* check that 'lined.no' is an integer */
}
struct _cffi_align_typedef_lined { char x; lined y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_lines(lines *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { polar(*tmp)[10] = &p->a; (void)tmp; }
  { polar(*tmp)[10] = &p->b; (void)tmp; }
}
struct _cffi_align_typedef_lines { char x; lines y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_nn(nn *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { line(*tmp)[50] = &p->pnt; (void)tmp; }
  (void)((p->no) | 0);  /* check that 'nn.no' is an integer */
}
struct _cffi_align_typedef_nn { char x; nn y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_point(point *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { float *tmp = &p->x; (void)tmp; }
  { float *tmp = &p->y; (void)tmp; }
}
struct _cffi_align_typedef_point { char x; point y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_polar(polar *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { float *tmp = &p->th; (void)tmp; }
  { float *tmp = &p->r; (void)tmp; }
  { point *tmp = &p->loc; (void)tmp; }
}
struct _cffi_align_typedef_polar { char x; polar y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_shape(shape *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { float *tmp = &p->dx; (void)tmp; }
  { float *tmp = &p->dy; (void)tmp; }
  { float *tmp = &p->dw; (void)tmp; }
  { float *tmp = &p->inv_mass; (void)tmp; }
  { float *tmp = &p->inv_inertia; (void)tmp; }
  { float *tmp = &p->restitution; (void)tmp; }
  { float *tmp = &p->friction; (void)tmp; }
  { polar * *tmp = &p->pnt; (void)tmp; }
  { point *tmp = &p->center; (void)tmp; }
  { float *tmp = &p->angle; (void)tmp; }
  { lines *tmp = &p->axis; (void)tmp; }
  (void)((p->no) | 0);  /* check that 'shape.no' is an integer */
}
struct _cffi_align_typedef_shape { char x; shape y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_xx(xx *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { int(*tmp)[800][500][3] = &p->rgb; (void)tmp; }
}
struct _cffi_align_typedef_xx { char x; xx y; };

static point _cffi_d_Centroid(array2 x0)
{
  return Centroid(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_Centroid(PyObject *self, PyObject *arg0)
{
  array2 x0;
  point result;
  PyObject *pyresult;

  if (_cffi_to_c((char *)&x0, _cffi_type(42), arg0) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = Centroid(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_struct((char *)&result, _cffi_type(1));
  return pyresult;
}
#else
static void _cffi_f_Centroid(point *result, array2 *x0)
{
  { *result = Centroid(*x0); }
}
#endif

static point _cffi_d_Lengthening(point x0, point x1, float x2, float x3)
{
  return Lengthening(x0, x1, x2, x3);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_Lengthening(PyObject *self, PyObject *args)
{
  point x0;
  point x1;
  float x2;
  float x3;
  point result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;

  if (!PyArg_UnpackTuple(args, "Lengthening", 4, 4, &arg0, &arg1, &arg2, &arg3))
    return NULL;

  if (_cffi_to_c((char *)&x0, _cffi_type(1), arg0) < 0)
    return NULL;

  if (_cffi_to_c((char *)&x1, _cffi_type(1), arg1) < 0)
    return NULL;

  x2 = (float)_cffi_to_c_float(arg2);
  if (x2 == (float)-1 && PyErr_Occurred())
    return NULL;

  x3 = (float)_cffi_to_c_float(arg3);
  if (x3 == (float)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = Lengthening(x0, x1, x2, x3); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_struct((char *)&result, _cffi_type(1));
  return pyresult;
}
#else
static void _cffi_f_Lengthening(point *result, point *x0, point *x1, float x2, float x3)
{
  { *result = Lengthening(*x0, *x1, x2, x3); }
}
#endif

static collision _cffi_d_SAT_Collide(shape * x0, shape * x1, bool x2, bool x3)
{
  return SAT_Collide(x0, x1, x2, x3);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_SAT_Collide(PyObject *self, PyObject *args)
{
  shape * x0;
  shape * x1;
  bool x2;
  bool x3;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  collision result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;

  if (!PyArg_UnpackTuple(args, "SAT_Collide", 4, 4, &arg0, &arg1, &arg2, &arg3))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(18), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (shape *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(18), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(18), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (shape *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(18), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x2, _cffi_type(24), arg2) < 0)
    return NULL;

  if (_cffi_to_c((char *)&x3, _cffi_type(24), arg3) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = SAT_Collide(x0, x1, x2, x3); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_struct((char *)&result, _cffi_type(74));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
static void _cffi_f_SAT_Collide(collision *result, shape * x0, shape * x1, bool x2, bool x3)
{
  { *result = SAT_Collide(x0, x1, x2, x3); }
}
#endif

static float _cffi_d_angle(point x0, point x1)
{
  return angle(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_angle(PyObject *self, PyObject *args)
{
  point x0;
  point x1;
  float result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "angle", 2, 2, &arg0, &arg1))
    return NULL;

  if (_cffi_to_c((char *)&x0, _cffi_type(1), arg0) < 0)
    return NULL;

  if (_cffi_to_c((char *)&x1, _cffi_type(1), arg1) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = angle(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_float(result);
  return pyresult;
}
#else
static float _cffi_f_angle(point *x0, point *x1)
{
  float result;
  { result = angle(*x0, *x1); }
  return result;
}
#endif

static collision _cffi_d_circle_circle(shape * x0, shape * x1)
{
  return circle_circle(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_circle_circle(PyObject *self, PyObject *args)
{
  shape * x0;
  shape * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  collision result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "circle_circle", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(18), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (shape *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(18), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(18), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (shape *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(18), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = circle_circle(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_struct((char *)&result, _cffi_type(74));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
static void _cffi_f_circle_circle(collision *result, shape * x0, shape * x1)
{
  { *result = circle_circle(x0, x1); }
}
#endif

static collision _cffi_d_circle_polygon(shape * x0, shape * x1)
{
  return circle_polygon(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_circle_polygon(PyObject *self, PyObject *args)
{
  shape * x0;
  shape * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  collision result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "circle_polygon", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(18), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (shape *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(18), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(18), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (shape *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(18), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = circle_polygon(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_struct((char *)&result, _cffi_type(74));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
static void _cffi_f_circle_polygon(collision *result, shape * x0, shape * x1)
{
  { *result = circle_polygon(x0, x1); }
}
#endif

static void _cffi_d_destroyShape(shape * x0)
{
  destroyShape(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_destroyShape(PyObject *self, PyObject *arg0)
{
  shape * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(18), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (shape *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(18), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { destroyShape(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_destroyShape _cffi_d_destroyShape
#endif

static void _cffi_d_destroylight(xx * x0)
{
  destroylight(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_destroylight(PyObject *self, PyObject *arg0)
{
  xx * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(77), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (xx *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(77), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { destroylight(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_destroylight _cffi_d_destroylight
#endif

static void _cffi_d_destroylights(dd * x0)
{
  destroylights(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_destroylights(PyObject *self, PyObject *arg0)
{
  dd * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(66), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (dd *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(66), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { destroylights(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_destroylights _cffi_d_destroylights
#endif

static float _cffi_d_distance2p(point x0, point x1)
{
  return distance2p(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_distance2p(PyObject *self, PyObject *args)
{
  point x0;
  point x1;
  float result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "distance2p", 2, 2, &arg0, &arg1))
    return NULL;

  if (_cffi_to_c((char *)&x0, _cffi_type(1), arg0) < 0)
    return NULL;

  if (_cffi_to_c((char *)&x1, _cffi_type(1), arg1) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = distance2p(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_float(result);
  return pyresult;
}
#else
static float _cffi_f_distance2p(point *x0, point *x1)
{
  float result;
  { result = distance2p(*x0, *x1); }
  return result;
}
#endif

static lines _cffi_d_getaxis(array2 x0, point x1)
{
  return getaxis(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_getaxis(PyObject *self, PyObject *args)
{
  array2 x0;
  point x1;
  lines result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "getaxis", 2, 2, &arg0, &arg1))
    return NULL;

  if (_cffi_to_c((char *)&x0, _cffi_type(42), arg0) < 0)
    return NULL;

  if (_cffi_to_c((char *)&x1, _cffi_type(1), arg1) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = getaxis(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_struct((char *)&result, _cffi_type(103));
  return pyresult;
}
#else
static void _cffi_f_getaxis(lines *result, array2 *x0, point *x1)
{
  { *result = getaxis(*x0, *x1); }
}
#endif

static checkpoint _cffi_d_intersection(point x0, point x1, point x2, point x3)
{
  return intersection(x0, x1, x2, x3);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_intersection(PyObject *self, PyObject *args)
{
  point x0;
  point x1;
  point x2;
  point x3;
  checkpoint result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;

  if (!PyArg_UnpackTuple(args, "intersection", 4, 4, &arg0, &arg1, &arg2, &arg3))
    return NULL;

  if (_cffi_to_c((char *)&x0, _cffi_type(1), arg0) < 0)
    return NULL;

  if (_cffi_to_c((char *)&x1, _cffi_type(1), arg1) < 0)
    return NULL;

  if (_cffi_to_c((char *)&x2, _cffi_type(1), arg2) < 0)
    return NULL;

  if (_cffi_to_c((char *)&x3, _cffi_type(1), arg3) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = intersection(x0, x1, x2, x3); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_struct((char *)&result, _cffi_type(86));
  return pyresult;
}
#else
static void _cffi_f_intersection(checkpoint *result, point *x0, point *x1, point *x2, point *x3)
{
  { *result = intersection(*x0, *x1, *x2, *x3); }
}
#endif

static bool _cffi_d_isBetween(point x0, point x1, point x2, point x3)
{
  return isBetween(x0, x1, x2, x3);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_isBetween(PyObject *self, PyObject *args)
{
  point x0;
  point x1;
  point x2;
  point x3;
  bool result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;

  if (!PyArg_UnpackTuple(args, "isBetween", 4, 4, &arg0, &arg1, &arg2, &arg3))
    return NULL;

  if (_cffi_to_c((char *)&x0, _cffi_type(1), arg0) < 0)
    return NULL;

  if (_cffi_to_c((char *)&x1, _cffi_type(1), arg1) < 0)
    return NULL;

  if (_cffi_to_c((char *)&x2, _cffi_type(1), arg2) < 0)
    return NULL;

  if (_cffi_to_c((char *)&x3, _cffi_type(1), arg3) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = isBetween(x0, x1, x2, x3); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(24));
  return pyresult;
}
#else
static bool _cffi_f_isBetween(point *x0, point *x1, point *x2, point *x3)
{
  bool result;
  { result = isBetween(*x0, *x1, *x2, *x3); }
  return result;
}
#endif

static xx * _cffi_d_light(point x0, int x1)
{
  return light(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_light(PyObject *self, PyObject *args)
{
  point x0;
  int x1;
  xx * result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "light", 2, 2, &arg0, &arg1))
    return NULL;

  if (_cffi_to_c((char *)&x0, _cffi_type(1), arg0) < 0)
    return NULL;

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = light(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(77));
  return pyresult;
}
#else
static xx * _cffi_f_light(point *x0, int x1)
{
  xx * result;
  { result = light(*x0, x1); }
  return result;
}
#endif

static dd * _cffi_d_lights(shape * * x0, int x1, point x2, float x3)
{
  return lights(x0, x1, x2, x3);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_lights(PyObject *self, PyObject *args)
{
  shape * * x0;
  int x1;
  point x2;
  float x3;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  dd * result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;

  if (!PyArg_UnpackTuple(args, "lights", 4, 4, &arg0, &arg1, &arg2, &arg3))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(28), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (shape * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(28), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  if (_cffi_to_c((char *)&x2, _cffi_type(1), arg2) < 0)
    return NULL;

  x3 = (float)_cffi_to_c_float(arg3);
  if (x3 == (float)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = lights(x0, x1, x2, x3); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(66));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
static dd * _cffi_f_lights(shape * * x0, int x1, point *x2, float x3)
{
  dd * result;
  { result = lights(x0, x1, *x2, x3); }
  return result;
}
#endif

static float _cffi_d_maximum(float x0, float x1)
{
  return maximum(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_maximum(PyObject *self, PyObject *args)
{
  float x0;
  float x1;
  float result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "maximum", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = (float)_cffi_to_c_float(arg0);
  if (x0 == (float)-1 && PyErr_Occurred())
    return NULL;

  x1 = (float)_cffi_to_c_float(arg1);
  if (x1 == (float)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = maximum(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_float(result);
  return pyresult;
}
#else
#  define _cffi_f_maximum _cffi_d_maximum
#endif

static point _cffi_d_midpoint(point x0, point x1)
{
  return midpoint(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_midpoint(PyObject *self, PyObject *args)
{
  point x0;
  point x1;
  point result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "midpoint", 2, 2, &arg0, &arg1))
    return NULL;

  if (_cffi_to_c((char *)&x0, _cffi_type(1), arg0) < 0)
    return NULL;

  if (_cffi_to_c((char *)&x1, _cffi_type(1), arg1) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = midpoint(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_struct((char *)&result, _cffi_type(1));
  return pyresult;
}
#else
static void _cffi_f_midpoint(point *result, point *x0, point *x1)
{
  { *result = midpoint(*x0, *x1); }
}
#endif

static float _cffi_d_minimum(float x0, float x1)
{
  return minimum(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_minimum(PyObject *self, PyObject *args)
{
  float x0;
  float x1;
  float result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "minimum", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = (float)_cffi_to_c_float(arg0);
  if (x0 == (float)-1 && PyErr_Occurred())
    return NULL;

  x1 = (float)_cffi_to_c_float(arg1);
  if (x1 == (float)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = minimum(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_float(result);
  return pyresult;
}
#else
#  define _cffi_f_minimum _cffi_d_minimum
#endif

static shape * _cffi_d_newShape(array2 x0, float x1, float x2, float x3, float x4)
{
  return newShape(x0, x1, x2, x3, x4);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_newShape(PyObject *self, PyObject *args)
{
  array2 x0;
  float x1;
  float x2;
  float x3;
  float x4;
  shape * result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;

  if (!PyArg_UnpackTuple(args, "newShape", 5, 5, &arg0, &arg1, &arg2, &arg3, &arg4))
    return NULL;

  if (_cffi_to_c((char *)&x0, _cffi_type(42), arg0) < 0)
    return NULL;

  x1 = (float)_cffi_to_c_float(arg1);
  if (x1 == (float)-1 && PyErr_Occurred())
    return NULL;

  x2 = (float)_cffi_to_c_float(arg2);
  if (x2 == (float)-1 && PyErr_Occurred())
    return NULL;

  x3 = (float)_cffi_to_c_float(arg3);
  if (x3 == (float)-1 && PyErr_Occurred())
    return NULL;

  x4 = (float)_cffi_to_c_float(arg4);
  if (x4 == (float)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = newShape(x0, x1, x2, x3, x4); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(18));
  return pyresult;
}
#else
static shape * _cffi_f_newShape(array2 *x0, float x1, float x2, float x3, float x4)
{
  shape * result;
  { result = newShape(*x0, x1, x2, x3, x4); }
  return result;
}
#endif

static collision _cffi_d_point_circle(shape * x0, shape * x1)
{
  return point_circle(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_point_circle(PyObject *self, PyObject *args)
{
  shape * x0;
  shape * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  collision result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "point_circle", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(18), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (shape *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(18), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(18), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (shape *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(18), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = point_circle(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_struct((char *)&result, _cffi_type(74));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
static void _cffi_f_point_circle(collision *result, shape * x0, shape * x1)
{
  { *result = point_circle(x0, x1); }
}
#endif

static collision _cffi_d_point_polygon(shape * x0, shape * x1)
{
  return point_polygon(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_point_polygon(PyObject *self, PyObject *args)
{
  shape * x0;
  shape * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  collision result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "point_polygon", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(18), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (shape *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(18), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(18), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (shape *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(18), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = point_polygon(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_struct((char *)&result, _cffi_type(74));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
static void _cffi_f_point_polygon(collision *result, shape * x0, shape * x1)
{
  { *result = point_polygon(x0, x1); }
}
#endif

static collision _cffi_d_polygon_polygon(shape * x0, shape * x1)
{
  return polygon_polygon(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_polygon_polygon(PyObject *self, PyObject *args)
{
  shape * x0;
  shape * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  collision result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "polygon_polygon", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(18), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (shape *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(18), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(18), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (shape *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(18), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = polygon_polygon(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_struct((char *)&result, _cffi_type(74));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
static void _cffi_f_polygon_polygon(collision *result, shape * x0, shape * x1)
{
  { *result = polygon_polygon(x0, x1); }
}
#endif

static checkpoint _cffi_d_projection(point x0, point x1, point x2)
{
  return projection(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_projection(PyObject *self, PyObject *args)
{
  point x0;
  point x1;
  point x2;
  checkpoint result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "projection", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  if (_cffi_to_c((char *)&x0, _cffi_type(1), arg0) < 0)
    return NULL;

  if (_cffi_to_c((char *)&x1, _cffi_type(1), arg1) < 0)
    return NULL;

  if (_cffi_to_c((char *)&x2, _cffi_type(1), arg2) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = projection(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_struct((char *)&result, _cffi_type(86));
  return pyresult;
}
#else
static void _cffi_f_projection(checkpoint *result, point *x0, point *x1, point *x2)
{
  { *result = projection(*x0, *x1, *x2); }
}
#endif

static void _cffi_d_resolveCollision(shape * x0, shape * x1, collision x2)
{
  resolveCollision(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_resolveCollision(PyObject *self, PyObject *args)
{
  shape * x0;
  shape * x1;
  collision x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "resolveCollision", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(18), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (shape *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(18), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(18), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (shape *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(18), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x2, _cffi_type(74), arg2) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { resolveCollision(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
static void _cffi_f_resolveCollision(shape * x0, shape * x1, collision *x2)
{
  { resolveCollision(x0, x1, *x2); }
}
#endif

static void _cffi_d_resolvePhysics(shape * x0, shape * x1, collision x2)
{
  resolvePhysics(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_resolvePhysics(PyObject *self, PyObject *args)
{
  shape * x0;
  shape * x1;
  collision x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "resolvePhysics", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(18), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (shape *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(18), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(18), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (shape *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(18), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x2, _cffi_type(74), arg2) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { resolvePhysics(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
static void _cffi_f_resolvePhysics(shape * x0, shape * x1, collision *x2)
{
  { resolvePhysics(x0, x1, *x2); }
}
#endif

static void _cffi_d_updateShape(shape * x0)
{
  updateShape(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_updateShape(PyObject *self, PyObject *arg0)
{
  shape * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(18), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (shape *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(18), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { updateShape(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_updateShape _cffi_d_updateShape
#endif

static const struct _cffi_global_s _cffi_globals[] = {
  { "Centroid", (void *)_cffi_f_Centroid, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 45), (void *)_cffi_d_Centroid },
  { "Lengthening", (void *)_cffi_f_Lengthening, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 52), (void *)_cffi_d_Lengthening },
  { "SAT_Collide", (void *)_cffi_f_SAT_Collide, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 21), (void *)_cffi_d_SAT_Collide },
  { "angle", (void *)_cffi_f_angle, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 37), (void *)_cffi_d_angle },
  { "circle_circle", (void *)_cffi_f_circle_circle, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 17), (void *)_cffi_d_circle_circle },
  { "circle_polygon", (void *)_cffi_f_circle_polygon, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 17), (void *)_cffi_d_circle_polygon },
  { "destroyShape", (void *)_cffi_f_destroyShape, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 68), (void *)_cffi_d_destroyShape },
  { "destroylight", (void *)_cffi_f_destroylight, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 76), (void *)_cffi_d_destroylight },
  { "destroylights", (void *)_cffi_f_destroylights, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 65), (void *)_cffi_d_destroylights },
  { "distance2p", (void *)_cffi_f_distance2p, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 37), (void *)_cffi_d_distance2p },
  { "false", (void *)_cffi_const_false, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "getaxis", (void *)_cffi_f_getaxis, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 41), (void *)_cffi_d_getaxis },
  { "intersection", (void *)_cffi_f_intersection, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 11), (void *)_cffi_d_intersection },
  { "isBetween", (void *)_cffi_f_isBetween, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_isBetween },
  { "light", (void *)_cffi_f_light, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 79), (void *)_cffi_d_light },
  { "lights", (void *)_cffi_f_lights, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 27), (void *)_cffi_d_lights },
  { "maximum", (void *)_cffi_f_maximum, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 33), (void *)_cffi_d_maximum },
  { "midpoint", (void *)_cffi_f_midpoint, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 48), (void *)_cffi_d_midpoint },
  { "minimum", (void *)_cffi_f_minimum, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 33), (void *)_cffi_d_minimum },
  { "newShape", (void *)_cffi_f_newShape, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 58), (void *)_cffi_d_newShape },
  { "point_circle", (void *)_cffi_f_point_circle, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 17), (void *)_cffi_d_point_circle },
  { "point_polygon", (void *)_cffi_f_point_polygon, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 17), (void *)_cffi_d_point_polygon },
  { "polygon_polygon", (void *)_cffi_f_polygon_polygon, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 17), (void *)_cffi_d_polygon_polygon },
  { "projection", (void *)_cffi_f_projection, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 6), (void *)_cffi_d_projection },
  { "resolveCollision", (void *)_cffi_f_resolveCollision, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 71), (void *)_cffi_d_resolveCollision },
  { "resolvePhysics", (void *)_cffi_f_resolvePhysics, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 71), (void *)_cffi_d_resolvePhysics },
  { "true", (void *)_cffi_const_true, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "updateShape", (void *)_cffi_f_updateShape, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 68), (void *)_cffi_d_updateShape },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "flt", offsetof(array, flt),
           sizeof(((array *)0)->flt),
           _CFFI_OP(_CFFI_OP_NOOP, 89) },
  { "bl", offsetof(array, bl),
          sizeof(((array *)0)->bl),
          _CFFI_OP(_CFFI_OP_NOOP, 84) },
  { "pnt", offsetof(array, pnt),
           sizeof(((array *)0)->pnt),
           _CFFI_OP(_CFFI_OP_NOOP, 105) },
  { "pnt", offsetof(array2, pnt),
           sizeof(((array2 *)0)->pnt),
           _CFFI_OP(_CFFI_OP_NOOP, 105) },
  { "no", offsetof(array2, no),
          sizeof(((array2 *)0)->no),
          _CFFI_OP(_CFFI_OP_NOOP, 29) },
  { "pnt", offsetof(checkpoint, pnt),
           sizeof(((checkpoint *)0)->pnt),
           _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "check", offsetof(checkpoint, check),
             sizeof(((checkpoint *)0)->check),
             _CFFI_OP(_CFFI_OP_NOOP, 24) },
  { "check", offsetof(collision, check),
             sizeof(((collision *)0)->check),
             _CFFI_OP(_CFFI_OP_NOOP, 24) },
  { "mtv", offsetof(collision, mtv),
           sizeof(((collision *)0)->mtv),
           _CFFI_OP(_CFFI_OP_NOOP, 110) },
  { "contacts", offsetof(collision, contacts),
                sizeof(((collision *)0)->contacts),
                _CFFI_OP(_CFFI_OP_NOOP, 118) },
  { "pnt", offsetof(dd, pnt),
           sizeof(((dd *)0)->pnt),
           _CFFI_OP(_CFFI_OP_NOOP, 109) },
  { "no", offsetof(dd, no),
          sizeof(((dd *)0)->no),
          _CFFI_OP(_CFFI_OP_NOOP, 29) },
  { "shaped", offsetof(ff, shaped),
              sizeof(((ff *)0)->shaped),
              _CFFI_OP(_CFFI_OP_NOOP, 126) },
  { "no", offsetof(ff, no),
          sizeof(((ff *)0)->no),
          _CFFI_OP(_CFFI_OP_NOOP, 29) },
  { "mtv", offsetof(gg, mtv),
           sizeof(((gg *)0)->mtv),
           _CFFI_OP(_CFFI_OP_NOOP, 110) },
  { "pnt", offsetof(gg, pnt),
           sizeof(((gg *)0)->pnt),
           _CFFI_OP(_CFFI_OP_NOOP, 109) },
  { "no", offsetof(gg, no),
          sizeof(((gg *)0)->no),
          _CFFI_OP(_CFFI_OP_NOOP, 29) },
  { "center", offsetof(gg, center),
              sizeof(((gg *)0)->center),
              _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "axis", offsetof(gg, axis),
            sizeof(((gg *)0)->axis),
            _CFFI_OP(_CFFI_OP_NOOP, 103) },
  { "prj", offsetof(gg, prj),
           sizeof(((gg *)0)->prj),
           _CFFI_OP(_CFFI_OP_NOOP, 120) },
  { "ptr", offsetof(inrng, ptr),
           sizeof(((inrng *)0)->ptr),
           _CFFI_OP(_CFFI_OP_NOOP, 115) },
  { "no", offsetof(inrng, no),
          sizeof(((inrng *)0)->no),
          _CFFI_OP(_CFFI_OP_NOOP, 29) },
  { "p1", offsetof(line, p1),
          sizeof(((line *)0)->p1),
          _CFFI_OP(_CFFI_OP_NOOP, 110) },
  { "p2", offsetof(line, p2),
          sizeof(((line *)0)->p2),
          _CFFI_OP(_CFFI_OP_NOOP, 110) },
  { "p1", offsetof(lined, p1),
          sizeof(((lined *)0)->p1),
          _CFFI_OP(_CFFI_OP_NOOP, 111) },
  { "p2", offsetof(lined, p2),
          sizeof(((lined *)0)->p2),
          _CFFI_OP(_CFFI_OP_NOOP, 111) },
  { "no", offsetof(lined, no),
          sizeof(((lined *)0)->no),
          _CFFI_OP(_CFFI_OP_NOOP, 29) },
  { "a", offsetof(lines, a),
         sizeof(((lines *)0)->a),
         _CFFI_OP(_CFFI_OP_NOOP, 113) },
  { "b", offsetof(lines, b),
         sizeof(((lines *)0)->b),
         _CFFI_OP(_CFFI_OP_NOOP, 113) },
  { "pnt", offsetof(nn, pnt),
           sizeof(((nn *)0)->pnt),
           _CFFI_OP(_CFFI_OP_NOOP, 100) },
  { "no", offsetof(nn, no),
          sizeof(((nn *)0)->no),
          _CFFI_OP(_CFFI_OP_NOOP, 29) },
  { "x", offsetof(point, x),
         sizeof(((point *)0)->x),
         _CFFI_OP(_CFFI_OP_NOOP, 31) },
  { "y", offsetof(point, y),
         sizeof(((point *)0)->y),
         _CFFI_OP(_CFFI_OP_NOOP, 31) },
  { "th", offsetof(polar, th),
          sizeof(((polar *)0)->th),
          _CFFI_OP(_CFFI_OP_NOOP, 31) },
  { "r", offsetof(polar, r),
         sizeof(((polar *)0)->r),
         _CFFI_OP(_CFFI_OP_NOOP, 31) },
  { "loc", offsetof(polar, loc),
           sizeof(((polar *)0)->loc),
           _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "dx", offsetof(shape, dx),
          sizeof(((shape *)0)->dx),
          _CFFI_OP(_CFFI_OP_NOOP, 31) },
  { "dy", offsetof(shape, dy),
          sizeof(((shape *)0)->dy),
          _CFFI_OP(_CFFI_OP_NOOP, 31) },
  { "dw", offsetof(shape, dw),
          sizeof(((shape *)0)->dw),
          _CFFI_OP(_CFFI_OP_NOOP, 31) },
  { "inv_mass", offsetof(shape, inv_mass),
                sizeof(((shape *)0)->inv_mass),
                _CFFI_OP(_CFFI_OP_NOOP, 31) },
  { "inv_inertia", offsetof(shape, inv_inertia),
                   sizeof(((shape *)0)->inv_inertia),
                   _CFFI_OP(_CFFI_OP_NOOP, 31) },
  { "restitution", offsetof(shape, restitution),
                   sizeof(((shape *)0)->restitution),
                   _CFFI_OP(_CFFI_OP_NOOP, 31) },
  { "friction", offsetof(shape, friction),
                sizeof(((shape *)0)->friction),
                _CFFI_OP(_CFFI_OP_NOOP, 31) },
  { "pnt", offsetof(shape, pnt),
           sizeof(((shape *)0)->pnt),
           _CFFI_OP(_CFFI_OP_NOOP, 109) },
  { "center", offsetof(shape, center),
              sizeof(((shape *)0)->center),
              _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "angle", offsetof(shape, angle),
             sizeof(((shape *)0)->angle),
             _CFFI_OP(_CFFI_OP_NOOP, 31) },
  { "axis", offsetof(shape, axis),
            sizeof(((shape *)0)->axis),
            _CFFI_OP(_CFFI_OP_NOOP, 103) },
  { "no", offsetof(shape, no),
          sizeof(((shape *)0)->no),
          _CFFI_OP(_CFFI_OP_NOOP, 29) },
  { "rgb", offsetof(xx, rgb),
           sizeof(((xx *)0)->rgb),
           _CFFI_OP(_CFFI_OP_NOOP, 97) },
  { "pnt", (size_t)-1,
           (size_t)-1,
           _CFFI_OP(_CFFI_OP_NOOP, 107) },
  { "no", (size_t)-1,
          (size_t)-1,
          _CFFI_OP(_CFFI_OP_NOOP, 29) },
  { "p", (size_t)-1,
         (size_t)-1,
         _CFFI_OP(_CFFI_OP_NOOP, 123) },
  { "prj", (size_t)-1,
           (size_t)-1,
           _CFFI_OP(_CFFI_OP_NOOP, 113) },
  { "con", (size_t)-1,
           (size_t)-1,
           _CFFI_OP(_CFFI_OP_NOOP, 24) },
  { "minimum", (size_t)-1,
               (size_t)-1,
               _CFFI_OP(_CFFI_OP_NOOP, 110) },
  { "dist", (size_t)-1,
            (size_t)-1,
            _CFFI_OP(_CFFI_OP_NOOP, 110) },
  { "pnt", (size_t)-1,
           (size_t)-1,
           _CFFI_OP(_CFFI_OP_NOOP, 113) },
  { "no", (size_t)-1,
          (size_t)-1,
          _CFFI_OP(_CFFI_OP_NOOP, 29) },
  { "sorted", (size_t)-1,
              (size_t)-1,
              _CFFI_OP(_CFFI_OP_NOOP, 24) },
  { "center", (size_t)-1,
              (size_t)-1,
              _CFFI_OP(_CFFI_OP_NOOP, 1) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "$1", 118, _CFFI_F_CHECK_FIELDS,
    (size_t)-2, -2, 49, 2 /* unnamed */ },
  { "$2", 119, _CFFI_F_CHECK_FIELDS,
    (size_t)-2, -2, 51, 1 /* unnamed */ },
  { "$3", 122, _CFFI_F_CHECK_FIELDS,
    (size_t)-2, -2, 52, 4 /* unnamed */ },
  { "$4", 125, _CFFI_F_CHECK_FIELDS,
    (size_t)-2, -2, 56, 4 /* unnamed */ },
  { "$array", 83, _CFFI_F_CHECK_FIELDS,
    sizeof(array), offsetof(struct _cffi_align_typedef_array, y), 0, 3 },
  { "$array2", 42, _CFFI_F_CHECK_FIELDS,
    sizeof(array2), offsetof(struct _cffi_align_typedef_array2, y), 3, 2 },
  { "$checkpoint", 86, _CFFI_F_CHECK_FIELDS,
    sizeof(checkpoint), offsetof(struct _cffi_align_typedef_checkpoint, y), 5, 2 },
  { "$collision", 74, _CFFI_F_CHECK_FIELDS,
    sizeof(collision), offsetof(struct _cffi_align_typedef_collision, y), 7, 3 },
  { "$dd", 87, _CFFI_F_CHECK_FIELDS,
    sizeof(dd), offsetof(struct _cffi_align_typedef_dd, y), 10, 2 },
  { "$ff", 88, _CFFI_F_CHECK_FIELDS,
    sizeof(ff), offsetof(struct _cffi_align_typedef_ff, y), 12, 2 },
  { "$gg", 91, _CFFI_F_CHECK_FIELDS,
    sizeof(gg), offsetof(struct _cffi_align_typedef_gg, y), 14, 6 },
  { "$inrng", 92, _CFFI_F_CHECK_FIELDS,
    sizeof(inrng), offsetof(struct _cffi_align_typedef_inrng, y), 20, 2 },
  { "$line", 99, _CFFI_F_CHECK_FIELDS,
    sizeof(line), offsetof(struct _cffi_align_typedef_line, y), 22, 2 },
  { "$lined", 102, _CFFI_F_CHECK_FIELDS,
    sizeof(lined), offsetof(struct _cffi_align_typedef_lined, y), 24, 3 },
  { "$lines", 103, _CFFI_F_CHECK_FIELDS,
    sizeof(lines), offsetof(struct _cffi_align_typedef_lines, y), 27, 2 },
  { "$nn", 104, _CFFI_F_CHECK_FIELDS,
    sizeof(nn), offsetof(struct _cffi_align_typedef_nn, y), 29, 2 },
  { "$point", 1, _CFFI_F_CHECK_FIELDS,
    sizeof(point), offsetof(struct _cffi_align_typedef_point, y), 31, 2 },
  { "$polar", 110, _CFFI_F_CHECK_FIELDS,
    sizeof(polar), offsetof(struct _cffi_align_typedef_polar, y), 33, 3 },
  { "$shape", 117, _CFFI_F_CHECK_FIELDS,
    sizeof(shape), offsetof(struct _cffi_align_typedef_shape, y), 36, 12 },
  { "$xx", 129, _CFFI_F_CHECK_FIELDS,
    sizeof(xx), offsetof(struct _cffi_align_typedef_xx, y), 48, 1 },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "$bool", 24, _cffi_prim_int(sizeof(bool), ((bool)-1) <= 0),
    "false,true" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "array", 83 },
  { "array2", 42 },
  { "bool", 24 },
  { "checkpoint", 86 },
  { "collision", 74 },
  { "dd", 87 },
  { "ff", 88 },
  { "gg", 91 },
  { "inrng", 92 },
  { "line", 99 },
  { "lined", 102 },
  { "lines", 103 },
  { "nn", 104 },
  { "point", 1 },
  { "polar", 110 },
  { "shape", 117 },
  { "xx", 129 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  _cffi_typenames,
  28,  /* num_globals */
  20,  /* num_struct_unions */
  1,  /* num_enums */
  17,  /* num_typenames */
  NULL,  /* no includes */
  130,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_engine(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_engine(void) { return NULL; }
#  else
     initengine(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_engine(void)
{
  return _cffi_init("engine", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initengine(void)
{
  _cffi_init("engine", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
